name: Publish installer

on:
  workflow_dispatch

env:
  REGISTRY: ghcr.io
  tag: 0.1.0

jobs:
  publish-docker-image:
    runs-on: [ubuntu-latest]

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Set image name to github repository name in lowercase
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      #Checkout vultr/cluster-api-provider-vultr
      - name: Checkout vultr/cluster-api-provider-vultr
        uses: actions/checkout@v4
        with:
          repository: 'vultr/cluster-api-provider-vultr'

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #Build docker image
      - name: Build docker image
        run: |
          make docker-build docker-push CONTROLLER_IMAGE=${{env.REGISTRY}}/${{steps.imageNameToLowerCase.outputs.imageName}} TAG=${{env.tag}}
        
          