name: Publish installer release

on:
  workflow_dispatch

env:
  REGISTRY: ghcr.io
  tag: 0.1.0

jobs:
  publish-docker-image:
    runs-on: [ubuntu-latest]

    # permissions:
    #   contents: read
    #   packages: write
    #   attestations: write
    #   id-token: write

    steps:
      - id: imageNameToLowerCase
        name: Set image name to github repository name in lowercase
        run: |
          echo "image_name=${GITHUB_REPOSITORY,,}" >>$GITHUB_OUTPUT
          echo "image_name=${GITHUB_REPOSITORY,,}"

      - name: Checkout vultr/cluster-api-provider-vultr
        uses: actions/checkout@v4
        with:
          repository: 'vultr/cluster-api-provider-vultr'

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image and installer

        run: |
          make docker-build docker-push CONTROLLER_IMAGE=${{env.REGISTRY}}/${{steps.imageNameToLowerCase.outputs.image_name}} TAG=${{env.tag}}
          sed -i "s|image: .*|image: ${{env.REGISTRY}}/${{steps.imageNameToLowerCase.outputs.image_name}}:${{env.tag}}|g" ./config/default/manager_image_patch.yaml
          make build-installer CONTROLLER_IMAGE=${{env.REGISTRY}}/${{steps.imageNameToLowerCase.outputs.image_name}}:${{env.tag}}

      #The makefile build-installer target generates an 'install.yaml' file in the dist directory.
      #This file contains all the resources built with Kustomize, which are necessary to install this project without its dependencies.
      #We publish this install file to the GitHub Actions artifact store.
      #This file can be used to install the vultr capi provider to kubernetes cluster.
      - name: Upload install.yaml to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/install.yaml
          asset_name: install.yaml
          tag: ${{ env.tag }}
          overwrite: true
          body: "cluster-api-provider-vultr:${{env.tag}} - install.yaml file can be used to install the vultr capi provider to kubernetes cluster. You should replace 'yourapikey' to VULTR_API_KEY before installing"

      # - name: Archive install.yaml
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: install.yaml
      #     path: dist/install.yaml
          #retention-days: 0